"""'add photo_notice_shown to users'

Revision ID: 671c4324a674
Revises: dd6bf6dcbd91
Create Date: 2026-08-17 18:29:02.200384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671c4324a674'
down_revision: Union[str, Sequence[str], None] = 'dd6bf6dcbd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'photo_notice_shown', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_notice_shown')

    # ### end Alembic commands ###
