"""'add macro nutrient columns'

Revision ID: a67d730c59e6
Revises: e619b9e682bf
Create Date: 2026-09-04 08:09:37.901362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67d730c59e6'
down_revision: Union[str, Sequence[str], None] = 'e619b9e682bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_data_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber_per_100g', sa.Float(), nullable=True))

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber_g', sa.Float(), nullable=True))

    with op.batch_alter_table('resolution_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber_per_100g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resolution_cache', schema=None) as batch_op:
        batch_op.drop_column('fiber_per_100g')
        batch_op.drop_column('carbs_per_100g')
        batch_op.drop_column('fat_per_100g')
        batch_op.drop_column('protein_per_100g')

    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.drop_column('fiber_g')
        batch_op.drop_column('carbs_g')
        batch_op.drop_column('fat_g')
        batch_op.drop_column('protein_g')

    with op.batch_alter_table('food_data_rows', schema=None) as batch_op:
        batch_op.drop_column('fiber_per_100g')
        batch_op.drop_column('carbs_per_100g')
        batch_op.drop_column('fat_per_100g')
        batch_op.drop_column('protein_per_100g')

    # ### end Alembic commands ###
