"""initial schema

Revision ID: dd6bf6dcbd91
Revises: 
Create Date: 2026-08-16 12:26:20.255413

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd6bf6dcbd91'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_data_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name_en', sa.String(), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('aliases_it', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met_cache',
    sa.Column('normalized_key', sa.String(), nullable=False),
    sa.Column('met', sa.Float(), nullable=False),
    sa.Column('provenance', sa.Enum('tabella', 'llm', 'etichetta', 'off', name='provenance'), nullable=False),
    sa.Column('display_name_it', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('normalized_key')
    )
    op.create_table('met_data_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_it', sa.String(), nullable=False),
    sa.Column('intensity', sa.String(), nullable=True),
    sa.Column('met', sa.Float(), nullable=False),
    sa.Column('source_note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolution_cache',
    sa.Column('normalized_key', sa.String(), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('provenance', sa.Enum('tabella', 'llm', 'etichetta', 'off', name='provenance'), nullable=False),
    sa.Column('display_name_it', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('normalized_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sesso', sa.Enum('maschio', 'femmina', name='sesso'), nullable=True),
    sa.Column('data_nascita', sa.Date(), nullable=True),
    sa.Column('altezza_cm', sa.Float(), nullable=True),
    sa.Column('peso_obiettivo_kg', sa.Float(), nullable=True),
    sa.Column('ritmo', sa.Enum('lento', 'moderato', 'sostenuto', name='ritmo'), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_shown', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('activity_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('met', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('provenance', sa.Enum('tabella', 'llm', 'etichetta', 'off', name='provenance'), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_entries_performed_at'), ['performed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_entries_user_id'), ['user_id'], unique=False)

    op.create_table('activity_level_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('livello', sa.Enum('sedentario', 'leggero', 'moderato', 'attivo', 'molto_attivo', name='livelloattivita'), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_level_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_level_history_user_id'), ['user_id'], unique=False)

    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('kcal_per_100g', sa.Float(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('provenance', sa.Enum('tabella', 'llm', 'etichetta', 'off', name='provenance'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_entries_consumed_at'), ['consumed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_entries_user_id'), ['user_id'], unique=False)

    op.create_table('pending_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.Enum('onboarding', 'food', 'weight', 'activity', 'correction', name='draftintent'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('awaiting_field', sa.String(), nullable=True),
    sa.Column('target_entry_id', sa.Integer(), nullable=True),
    sa.Column('target_entry_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_drafts_user_id'), ['user_id'], unique=True)

    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_weight_user_day')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_entries_day'))

    op.drop_table('weight_entries')
    with op.batch_alter_table('pending_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_drafts_user_id'))

    op.drop_table('pending_drafts')
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_entries_consumed_at'))

    op.drop_table('food_entries')
    with op.batch_alter_table('activity_level_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_level_history_user_id'))

    op.drop_table('activity_level_history')
    with op.batch_alter_table('activity_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_entries_performed_at'))

    op.drop_table('activity_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_user_id'))

    op.drop_table('users')
    op.drop_table('resolution_cache')
    op.drop_table('met_data_rows')
    op.drop_table('met_cache')
    op.drop_table('food_data_rows')
    # ### end Alembic commands ###
