"""make food_entries.grams nullable

Revision ID: e619b9e682bf
Revises: c3918c9bc23f
Create Date: 2026-08-23 18:52:27.044742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e619b9e682bf'
down_revision: Union[str, Sequence[str], None] = 'c3918c9bc23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('grams',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_entries', schema=None) as batch_op:
        batch_op.alter_column('grams',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
