"""'food table reference portions'

Revision ID: f337688dd975
Revises: 0cbfd74fa9aa
Create Date: 2026-09-05 14:34:27.800110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f337688dd975'
down_revision: Union[str, Sequence[str], None] = '0cbfd74fa9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_data_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portion_small_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('portion_medium_g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('portion_generous_g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_data_rows', schema=None) as batch_op:
        batch_op.drop_column('portion_generous_g')
        batch_op.drop_column('portion_medium_g')
        batch_op.drop_column('portion_small_g')

    # ### end Alembic commands ###
