"""'add advice_records table'

Revision ID: fef68af8bfe0
Revises: a67d730c59e6
Create Date: 2026-09-04 21:10:41.295730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef68af8bfe0'
down_revision: Union[str, Sequence[str], None] = 'a67d730c59e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Enum('dietician_review', 'daily_advice', 'advice_agent', name='advicesurface'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('topic', sa.Enum('meal_timing', 'logging_consistency', name='advicetopic'), nullable=True),
    sa.Column('outcome', sa.Enum('undetermined', 'followed', 'not_followed', name='adviceoutcome'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advice_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advice_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_advice_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advice_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advice_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_advice_records_created_at'))

    op.drop_table('advice_records')
    # ### end Alembic commands ###
