"""Offline tool to (re)generate Italian aliases for food_data.csv rows via the
configured LLM, for extending the bundled table later (design.md - 'Whether the
alias index is better generated by the language model at seed time or written by
hand' - open question). Not run automatically; the shipped aliases were hand-written
because no LLM endpoint was reachable while building this dataset (see DATA_SOURCES.md).

Usage:
    uv run python scripts/generate_aliases.py --only-missing

Writes results back to src/calobot/data/food_data.csv. Review the diff before
committing - this is meant to be a starting point for hand-correction, not a
trust-blindly output (design.md - "a bad translation is a data fix rather than a
debugging session").
"""

from __future__ import annotations

import argparse
import asyncio
import csv
from pathlib import Path

from pydantic import BaseModel

from calobot.llm.content import TextContent
from calobot.llm.gateway import LLMGateway
from calobot.settings import get_settings

DATA_PATH = Path(__file__).resolve().parents[1] / "src/calobot/data/food_data.csv"

SYSTEM_PROMPT = (
    "Sei un traduttore esperto di terminologia alimentare italiana. Dato il nome "
    "inglese di un alimento, restituisci 1-4 nomi o sinonimi italiani comuni con cui "
    "una persona lo scriverebbe in una chat, separati da punto e virgola. Rispondi "
    "solo con l'elenco, senza spiegazioni."
)


class AliasResult(BaseModel):
    aliases_it: list[str]


async def generate_aliases_for(gateway: LLMGateway, source_name_en: str) -> str:
    result = await gateway.call_structured(
        step="extract",
        system_prompt=SYSTEM_PROMPT,
        content=TextContent(text=source_name_en),
        schema=AliasResult,
    )
    return ";".join(a.strip() for a in result.aliases_it if a.strip())


async def main(only_missing: bool) -> None:
    settings = get_settings()
    gateway = LLMGateway(settings)

    with DATA_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    for row in rows:
        if only_missing and row["aliases_it"].strip():
            continue
        row["aliases_it"] = await generate_aliases_for(gateway, row["source_name_en"])
        print(f"{row['source_name_en']} -> {row['aliases_it']}")

    with DATA_PATH.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["source_name_en", "kcal_per_100g", "aliases_it"])
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--only-missing", action="store_true")
    args = parser.parse_args()
    asyncio.run(main(args.only_missing))
